SELECT ISNULL(MAX(CONVERT(NUMERIC(10),bltn_sntn_num))+1,0)
		SELECT REPLICATE('0',10-LEN(LTRIM(RTRIM(STR(ISNULL(MAX(CONVERT(NUMERIC(10),bltn_sntn_num)),0)+1))))) + LTRIM(RTRIM(STR(ISNULL(MAX(CONVERT(NUMERIC(10),bltn_sntn_num)),0)+1)))
          FROM KHCM..TD_BLTN_SNTN
		 WHERE blbr_num='0000000003'