SELECT B.CATEGORY
	  ,SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B 
INNER JOIN BOOK_SALES BS
on B.BOOK_ID=BS.BOOK_ID
WHERE TO_CHAR(BS.SALES_DATE,'YYYY-MM-DD') LIKE '%2022-01%' 
GROUP BY B.CATEGORY 
ORDER BY B.CATEGORY; 