SELECT A.AUTHOR_ID
      ,A.AUTHOR_NAME
      ,B.CATEGORY
      ,SUM(B.PRICE * BS.SALES) as TOTAL_SALES
FROM BOOK B
      INNER JOIN (SELECT * 
                     FROM BOOK_SALES 
                          WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') 
                                LIKE '2022-01%') BS
      on B.BOOK_ID=BS.BOOK_ID 
      INNER JOIN AUTHOR A
      on A.AUTHOR_ID=B.AUTHOR_ID
GROUP BY A.AUTHOR_ID,B.CATEGORY,A.AUTHOR_NAME
ORDER BY A.AUTHOR_ID,B.CATEGORY DESC ;